#!/bin/bash

echo "📋 Slackインタラクティブエンドポイント設定ガイド"
echo ""
echo "以下の手順でSlackアプリを設定してください："
echo ""
echo "1. https://api.slack.com/apps にアクセス"
echo "2. あなたのアプリ（daily-report-bot）を選択"
echo ""
echo "3. 左メニューから「Interactivity & Shortcuts」を選択"
echo ""
echo "4. 「Interactivity」をONにする"
echo ""
echo "5. 「Request URL」に以下を入力："
echo "   https://daily-report-bot-dcmks7y7vq-an.a.run.app/slack/interactive"
echo ""
echo "6. 「Save Changes」をクリック"
echo ""
echo "7. 左メニューから「Slash Commands」を選択"
echo ""
echo "8. 「/dailyreport」コマンドの「Request URL」を確認："
echo "   https://daily-report-bot-dcmks7y7vq-an.a.run.app/slack/command"
echo ""
echo "✅ 設定が完了したら、Slackで /dailyreport を実行してテストしてください"
